# Generated by Django 2.2 on 2019-04-25 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/men/')),
                ('product_name', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('garuntee', models.IntegerField()),
                ('pri', models.IntegerField()),
                ('catagories', models.CharField(choices=[('Digital', 'Digital'), ('Analogue', 'Analogue'), ('Automatic', 'Automatic'), ('Pilot', 'Pilot'), ('Chronograph', 'Chronograph'), ('Diving', 'Diving'), ('Mechanical', 'Mechanical'), ('Smart', 'Smart'), ('Luxury', 'Luxury')], default='', max_length=150)),
                ('size', models.CharField(choices=[('M', 'M'), ('L', 'L'), ('one-size', 'one-size'), ('pack', 'pack')], default='', max_length=50)),
                ('price_choice', models.CharField(choices=[('less than 500', 'less than 500'), ('500-1000', '500-1000'), ('1000-1500', '1000-1500'), ('1500-5000', '1500-5000'), ('5000_more', '5000_more')], default='', max_length=150)),
                ('disc', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('pri', models.IntegerField()),
                ('catagories', models.CharField(choices=[('Digital', 'Digital'), ('Analogue', 'Analogue'), ('Automatic', 'Automatic'), ('Pilot', 'Pilot'), ('Chronograph', 'Chronograph'), ('Diving', 'Diving'), ('Mechanical', 'Mechanical'), ('Smart', 'Smart'), ('Luxury', 'Luxury')], default='', max_length=150)),
                ('size', models.CharField(choices=[('M', 'M'), ('L', 'L'), ('one-size', 'one-size'), ('pack', 'pack')], default='', max_length=50)),
                ('disc', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paytype', models.CharField(choices=[('credit card', 'credit card'), ('debit card', 'debit card'), ('net banking', 'net banking')], max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('Account_number', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='men.product')),
            ],
        ),
    ]
