# Generated by Django 2.2 on 2019-04-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='product_name',
        ),
    ]
