# Generated by Django 2.2 on 2019-04-25 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0002_remove_payment_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='product_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='men.product'),
        ),
    ]
