# Generated by Django 2.1.4 on 2019-04-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
    ]
