# Generated by Django 2.2 on 2019-04-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190414_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.CharField(default='', max_length=50),
        ),
    ]
