# Generated by Django 2.2 on 2019-04-25 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190425_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.wishlist'),
        ),
    ]
