# Generated by Django 2.1.4 on 2019-03-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_auto_20190319_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='wo_product',
            name='image',
            field=models.ImageField(default='', upload_to='women/gallary'),
        ),
    ]
