# Generated by Django 2.1.4 on 2019-03-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_auto_20190328_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wo_product',
            old_name='image',
            new_name='img',
        ),
    ]
