# Generated by Django 2.1.4 on 2019-03-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_auto_20190328_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='wo_product',
            name='catagories',
            field=models.CharField(choices=[('Digital', 'Digital'), ('Analogue', 'Analogue'), ('Automatic', 'Automatic'), ('Pilot', 'Pilot'), ('Chronograph', 'Chronograph'), ('Diving', 'Diving'), ('Mechanical', 'Mechanical'), ('Smart', 'Smart'), ('Luxury', 'Luxury')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='wo_product',
            name='size',
            field=models.CharField(choices=[('M', 'M'), ('L', 'L'), ('one-size', 'one-size'), ('pack', 'pack')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wo_product',
            name='img',
            field=models.ImageField(upload_to='images/women/'),
        ),
    ]
