# Generated by Django 2.1.4 on 2019-04-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0007_auto_20190404_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('pri', models.IntegerField()),
                ('catagories', models.CharField(choices=[('Digital', 'Digital'), ('Analogue', 'Analogue'), ('Automatic', 'Automatic'), ('Pilot', 'Pilot'), ('Chronograph', 'Chronograph'), ('Diving', 'Diving'), ('Mechanical', 'Mechanical'), ('Smart', 'Smart'), ('Luxury', 'Luxury')], default='', max_length=150)),
                ('size', models.CharField(choices=[('M', 'M'), ('L', 'L'), ('one-size', 'one-size'), ('pack', 'pack')], default='', max_length=50)),
                ('disc', models.IntegerField(default='')),
            ],
        ),
    ]
