# Generated by Django 2.1.4 on 2019-04-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0008_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wo_product',
            name='disc',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='wo_product',
            name='price_choice',
            field=models.CharField(choices=[('less than 500', 'less than 500'), ('500-1000', '500-1000'), ('1000-1500', '1000-1500'), ('1500-5000', '1500-5000'), ('5000_more', '5000_more')], default='', max_length=150),
        ),
    ]
