# Generated by Django 2.1.4 on 2019-04-16 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0009_auto_20190414_1043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wishlist',
            new_name='wowishlist',
        ),
    ]
